# Generated by Django 3.0.7 on 2020-06-13 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 13, 5, 57, 53, 930606, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
